import { TripItinerary, DailyItinerary, buildSmartItinerary } from './calendar-export';

// Sample 3-day Berlin vegan trip itinerary
export function createSampleBerlinItinerary(): TripItinerary {
  
  // Accommodation details (A&O Berlin Mitte from our mock data)
  const accommodation = {
    name: "A&O Berlin Mitte",
    address: "Köpenicker Str. 127-129, 10179 Berlin, Germany",
    checkIn: new Date('2025-11-22T15:00:00'),
    checkOut: new Date('2025-11-24T11:00:00'),
    website: "https://www.aohostels.com/en/berlin/berlin-mitte/",
    safetyScore: 84
  };

  // Day 1: Friday - Arrival & Mitte/Kreuzberg
  const day1Venues = [
    {
      name: "Gratitude",
      address: "Warschauer Str. 33, 10243 Berlin, Germany",
      startTime: new Date('2025-11-22T10:00:00'),
      endTime: new Date('2025-11-22T11:30:00'),
      type: 'restaurant' as const,
      description: "Breakfast at Berlin's famous vegan café",
      website: "https://gratitude-eatery.de/",
      safetyScore: 92
    },
    {
      name: "Berlin Vegan Food Tour",
      address: "Hackescher Markt, 10178 Berlin, Germany",
      startTime: new Date('2025-11-22T14:00:00'),
      endTime: new Date('2025-11-22T18:00:00'),
      type: 'tour' as const,
      description: "Guided tour of Berlin's best vegan restaurants and markets with tastings",
      website: "https://www.getyourguide.com/berlin-l17/berlin-vegan-food-tour-t408673/",
      safetyScore: 94
    },
    {
      name: "Kopps",
      address: "Linienstraße 94, 10115 Berlin, Germany",
      startTime: new Date('2025-11-22T19:30:00'),
      endTime: new Date('2025-11-22T22:00:00'),
      type: 'restaurant' as const,
      description: "Upscale vegan fine dining - 4-course tasting menu",
      website: "https://kopps-berlin.de/en/",
      safetyScore: 98
    }
  ];

  // Day 2: Saturday - Neukölln & Markets
  const day2Venues = [
    {
      name: "The Plant Base",
      address: "Wrangelstraße 90, 10997 Berlin, Germany",
      startTime: new Date('2025-11-23T09:30:00'),
      endTime: new Date('2025-11-23T11:00:00'),
      type: 'restaurant' as const,
      description: "Hearty breakfast bowls and fresh juices",
      website: "https://theplantbase.berlin/",
      safetyScore: 89
    },
    {
      name: "Kreuzberg Culinary Food Tour",
      address: "Graefekiez, 10967 Berlin, Germany", 
      startTime: new Date('2025-11-23T12:00:00'),
      endTime: new Date('2025-11-23T15:00:00'),
      type: 'tour' as const,
      description: "Walking tour through Kreuzberg exploring multicultural food spots",
      website: "https://www.culinarywalkingtour.com/",
      safetyScore: 78
    },
    {
      name: "Alaska",
      address: "Reuterstraße 85, 12053 Berlin, Germany",
      startTime: new Date('2025-11-23T19:00:00'),
      endTime: new Date('2025-11-23T22:30:00'),
      type: 'restaurant' as const,
      description: "Vegan Spanish tapas bar with creative dishes and cocktails",
      website: "http://www.facebook.com/alaskabarberlin",
      safetyScore: 90
    }
  ];

  // Day 3: Sunday - Markets & Events
  const day3Venues = [
    {
      name: "Brammibal's Donuts",
      address: "Maybachufer 8, 12047 Berlin, Germany",
      startTime: new Date('2025-11-24T09:00:00'),
      endTime: new Date('2025-11-24T10:30:00'),
      type: 'restaurant' as const,
      description: "Famous Berlin vegan donut shop",
      website: "https://brammibalsdonuts.com/",
      safetyScore: 95
    },
    {
      name: "VeggiWorld Berlin",
      address: "Estrel Convention Center, Sonnenallee 225, 12057 Berlin",
      startTime: new Date('2025-11-24T11:00:00'),
      endTime: new Date('2025-11-24T15:00:00'),
      type: 'event' as const,
      description: "Europe's largest vegan trade fair with product demos and tastings",
      website: "https://veggiworld.com/",
      safetyScore: 91
    }
  ];

  // Build daily itineraries with smart scheduling and transit
  const day1Events = buildSmartItinerary(day1Venues, accommodation);
  const day2Events = buildSmartItinerary(day2Venues);
  const day3Events = buildSmartItinerary(day3Venues);

  const days: DailyItinerary[] = [
    {
      date: new Date('2025-11-22'),
      events: day1Events
    },
    {
      date: new Date('2025-11-23'),
      events: day2Events
    },
    {
      date: new Date('2025-11-24'),
      events: day3Events
    }
  ];

  return {
    title: "3-Day Vegan Berlin Adventure",
    description: "Complete vegan travel itinerary featuring the best plant-based restaurants, guided food tours, and community events in Berlin. Generated by NaVegate AI with actionable logistics and transit planning.",
    destination: "Berlin, Germany",
    days
  };
}

// Generate a realistic itinerary from chat conversation
export function generateItineraryFromChat(
  messages: Array<{ content: string; role: 'user' | 'assistant' }>,
  tripDetails?: {
    destination?: string;
    startDate?: Date;
    duration?: number;
    preferences?: {
      budgetRange?: string;
      eatingStyle?: string;
      planningStyle?: string;
    };
  }
): TripItinerary | null {
  // For now, return the sample itinerary
  // In production, this would parse the chat messages and extract venue recommendations
  
  // Simple heuristic: if conversation mentions Berlin and restaurants/venues, generate itinerary
  const chatContent = messages.map(m => m.content.toLowerCase()).join(' ');
  
  if (chatContent.includes('berlin') && 
      (chatContent.includes('restaurant') || chatContent.includes('food') || chatContent.includes('trip'))) {
    
    const baseItinerary = createSampleBerlinItinerary();
    
    // Customize based on trip details if provided
    if (tripDetails?.startDate) {
      const newStartDate = tripDetails.startDate;
      baseItinerary.days = baseItinerary.days.map((day, index) => ({
        ...day,
        date: new Date(newStartDate.getTime() + index * 24 * 60 * 60 * 1000),
        events: day.events.map(event => ({
          ...event,
          startTime: new Date(
            newStartDate.getTime() + 
            index * 24 * 60 * 60 * 1000 + 
            (event.startTime.getHours() * 60 + event.startTime.getMinutes()) * 60 * 1000
          ),
          endTime: new Date(
            newStartDate.getTime() + 
            index * 24 * 60 * 60 * 1000 + 
            (event.endTime.getHours() * 60 + event.endTime.getMinutes()) * 60 * 1000
          )
        }))
      }));
    }

    if (tripDetails?.destination) {
      baseItinerary.destination = tripDetails.destination;
    }

    return baseItinerary;
  }

  return null;
}

// Check if current conversation has enough detail for calendar export
export function canExportToCalendar(messages: Array<{ content: string; role: 'user' | 'assistant' }>): boolean {
  const chatContent = messages.map(m => m.content.toLowerCase()).join(' ');
  
  // Look for trip planning indicators
  const hasTripPlanning = chatContent.includes('trip') || 
                         chatContent.includes('itinerary') || 
                         chatContent.includes('plan my') ||
                         chatContent.includes('3-day') ||
                         chatContent.includes('weekend');
  
  const hasVenues = chatContent.includes('restaurant') || 
                   chatContent.includes('accommodation') || 
                   chatContent.includes('tour') ||
                   chatContent.includes('hotel');

  const hasLocation = chatContent.includes('berlin') || 
                     chatContent.includes('germany');

  return hasTripPlanning && hasVenues && hasLocation;
}